

POST http://localhost:3001/compile
Content-Type: application/json

{
    "maxExecutionTime": 20,
    "maxMemory": 4,
    "code": "I2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpewogIGludCBuOwogIHN0ZDo6Y2luID4+IG47CiAgc3RkOjpjb3V0IDw8ICJuIGVzdGUgIiA8PCBuOwp9Cg==",
    "tests": [{"input": "1234", "expectedOutput": "n este 1235"}, {"input": "1234", "expectedOutput": "n este 1234"}]
}

