

POST http://localhost:3001/compile
Content-Type: application/json

{
    "maxExecutionTime": 100,
    "maxMemory": 4,
    "code": "CiNpbmNsdWRlIDxpb3N0cmVhbT4KCmludCBtYWluKCkgewppbnQgbjsgY2luID4+IG47CnN0ZDo6Y291dCA8PCAibiBlc3RlICIgPDwgbjsKcmV0dXJuIDA7Cn0KCg=="
}

